# Generated by Django 6.1.1 on 2026-10-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('relative_path', models.TextField(unique=True)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk')],
            },
        ),
    ]
