# Generated by Django 6.1.1 on 2026-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
